from typing import Protocol
from ledger.domain.models import LedgerEntry

class LedgerRepository(Protocol):
    def append(self, entry: LedgerEntry) -> None: ...
    def entries_for(self, account_id: str) -> list[LedgerEntry]: ...
    def contains_entry(self, entry_id: str) -> bool: ...
